### ISSUE TITLE
Running Calcflow

### ISSUE THREAD

**Issue by Tomasvrba** [matryx/calcflow#3]
Hi Calcflow team, I work with VR and Data Visualization at the University of Alaska Fairbanks at http://www.dtn.alaska.edu/

Calcflow seems like an excellent tool that I would like to introduce to people here. I've cloned and downloaded your repo and tried running it in Unity with the HTC Vive. However, I am only getting a blank scene. Would you please have some more info or documentation how to interact with calcflow? The readme doesn't offer much information. 

Any help is appreciated. Looking forward to trying this promising tool!

Edit: I've had more success now running calcflow through Unity and exploring it. One particular instance I am having trouble with is the Parametrized Surface model. I haven't been successful in generating meshes and running animations . Again, any guidance would be much appreciated.

**Comment by EthanVanderHorn** [comment]
Hi, sorry you have been having some trouble. 

Can you elaborate on your problem? When you say you haven't been successful in generating meshes do you mean that graphing is not working? When you load into the parametrized surface scene is there a graph at all? What about other graphing scenes?

Also, if it is not too much trouble can you let me know what your initial problems were and how you solved them? I would be happy to update the readme in order to help future users.

**Comment by Tomasvrba** [comment]
Thank you Ethan! I won't be able to get back into testing Calcflow until Tuesday 9/26. If that's ok with you, I will send you a more detailed description then. And thanks for fixing the bug, I will pull the updated master and run it again next week.

**Comment by flpymonkey** [comment]
I am also having trouble starting the program! I am just getting a blank screen on start with the oculus rift. I do not see and scenes or exe files to run or any examples?
